# Generated by Django 2.1 on 2018-08-25 14:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pid', models.CharField(max_length=18, unique=True)),
                ('phone', models.CharField(max_length=120)),
                ('hukou', models.CharField(choices=[('C', '城市'), ('N', '农村')], max_length=8)),
                ('wechat', models.CharField(blank=True, max_length=50, null=True)),
                ('introducer', models.CharField(blank=True, max_length=30, null=True)),
                ('note', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=120, null=True)),
                ('im', models.CharField(blank=True, max_length=120, null=True)),
                ('note', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lowest_baseline', models.FloatField()),
                ('validFrom', models.DateField()),
                ('validTo', models.DateField()),
                ('note', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_base', models.FloatField()),
                ('validFrom', models.DateField()),
                ('validTo', models.DateField()),
                ('total_price', models.FloatField()),
                ('paymethod', models.CharField(choices=[('WX', '微信'), ('ZFB', '支付宝'), ('YHK', '银行卡')], max_length=3)),
                ('payaccount', models.CharField(max_length=30)),
                ('orderDate', models.DateField(default=datetime.datetime(2018, 8, 25, 14, 53, 33, 320221, tzinfo=utc))),
                ('price2Partner', models.FloatField(blank=True, default=0, null=True)),
                ('dealPlatform', models.CharField(blank=True, max_length=10, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sb.Customer')),
                ('district', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sb.District')),
                ('orderType', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sb.OrderType')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sb.Partner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sb.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svalidFrom', models.DateField()),
                ('svalidTo', models.DateField()),
                ('stotal_price', models.FloatField()),
                ('paymethod', models.CharField(choices=[('WX', '微信'), ('ZFB', '支付宝'), ('YHK', '银行卡')], max_length=3)),
                ('payaccount', models.CharField(max_length=30)),
                ('orderDate', models.DateField(default=datetime.datetime(2018, 8, 25, 14, 53, 33, 318220, tzinfo=utc))),
                ('sprice2Partner', models.FloatField(blank=True, default=0, null=True)),
                ('dealPlatform', models.CharField(blank=True, max_length=10, null=True)),
                ('snote', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sb.Customer')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sb.Partner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sb.Product')),
            ],
        ),
        migrations.CreateModel(
            name='User_extra_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('pid', models.CharField(max_length=18, unique=True)),
                ('realname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('comment', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='customers',
            field=models.ManyToManyField(through='sb.Product_Order', to='sb.Customer'),
        ),
    ]
