# Generated by Django 2.1 on 2018-08-25 14:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_order',
            name='orderDate',
            field=models.DateField(default=datetime.datetime(2018, 8, 25, 14, 54, 49, 475078, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='service_order',
            name='orderDate',
            field=models.DateField(default=datetime.datetime(2018, 8, 25, 14, 54, 49, 473076, tzinfo=utc)),
        ),
    ]
