# Generated by Django 3.0.4 on 2020-04-28 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0002_auto_20200428_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_order',
            name='payaccount',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='payaccount',
        ),
    ]
