# Generated by Django 2.0.6 on 2018-08-27 07:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0003_auto_20180827_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='product_order',
            name='dealPlatform',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='dealPlatform',
        ),
        migrations.AlterField(
            model_name='product_order',
            name='orderDate',
            field=models.DateField(default=datetime.datetime(2018, 8, 27, 7, 39, 34, 761385, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product_order',
            name='paymethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sb.PayMethod'),
        ),
        migrations.AlterField(
            model_name='service_order',
            name='orderDate',
            field=models.DateField(default=datetime.datetime(2018, 8, 27, 7, 39, 34, 759391, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='service_order',
            name='paymethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sb.PayMethod'),
        ),
    ]
