# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0003_user_extra_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_extra_info',
        ),
    ]
