# Generated by Django 3.0.4 on 2020-04-28 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0003_auto_20200428_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='lowest_baseline',
        ),
        migrations.RemoveField(
            model_name='product',
            name='validFrom',
        ),
        migrations.RemoveField(
            model_name='product',
            name='validTo',
        ),
    ]
