# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sb', '0004_delete_user_extra_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_extra_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('pid', models.CharField(max_length=18, unique=True)),
                ('realname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('comment', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
