# Generated by Django 2.0.6 on 2018-08-28 11:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0004_auto_20180827_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product_order',
            name='orderDate',
            field=models.DateField(default=datetime.datetime(2018, 8, 28, 11, 36, 18, 563122, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='service_order',
            name='orderDate',
            field=models.DateField(default=datetime.datetime(2018, 8, 28, 11, 36, 18, 561127, tzinfo=utc)),
        ),
    ]
