# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 03:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0006_auto_20170417_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.DateField(default=datetime.datetime(2017, 4, 20, 3, 49, 18, 69053, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=99),
        ),
    ]
