# Generated by Django 2.0.6 on 2018-08-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0007_auto_20180829_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
