# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 06:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0007_auto_20170419_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sgValidFrom',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='sgValidTo',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.DateField(default=datetime.datetime(2017, 4, 20, 6, 11, 2, 523252, tzinfo=utc)),
        ),
    ]
