# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 07:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0008_auto_20170419_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=120, null=True)),
                ('im', models.CharField(blank=True, max_length=120, null=True)),
                ('note', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('BJCY', '朝阳'), ('BJHD', '海淀'), ('BJDC', '东城'), ('BJXC', '西城'), ('BJFT', '丰台'), ('BJDX', '大兴'), ('BJTZ', '通州'), ('BJCP', '昌平'), ('BJHR', '怀柔'), ('BJPG', '平谷'), ('BJYQ', '延庆')], default='BJFT', max_length=5)),
                ('product_base', models.FloatField()),
                ('validFrom', models.DateField()),
                ('validTo', models.DateField()),
                ('total_price', models.FloatField()),
                ('price2Partner', models.FloatField()),
                ('paymethod', models.CharField(choices=[('WX', '微信'), ('ZFB', '支付宝'), ('YHK', '银行卡')], max_length=3)),
                ('payaccount', models.CharField(max_length=30)),
                ('orderDate', models.DateField(default=datetime.datetime(2017, 4, 21, 7, 27, 26, 284684, tzinfo=utc))),
                ('dealPlatform', models.CharField(blank=True, max_length=10, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validFrom', models.DateField()),
                ('validTo', models.DateField()),
                ('total_price', models.FloatField()),
                ('price2Partner', models.FloatField()),
                ('paymethod', models.CharField(choices=[('WX', '微信'), ('ZFB', '支付宝'), ('YHK', '银行卡')], max_length=3)),
                ('payaccount', models.CharField(max_length=30)),
                ('orderDate', models.DateField(default=datetime.datetime(2017, 4, 21, 7, 27, 26, 284684, tzinfo=utc))),
                ('dealPlatform', models.CharField(blank=True, max_length=10, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='baseline',
            new_name='lowest_baseline',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='district',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='product',
            name='customers',
            field=models.ManyToManyField(through='sb.Product_Order', to='sb.Customer'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='service_order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sb.Customer'),
        ),
        migrations.AddField(
            model_name='service_order',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sb.Partner'),
        ),
        migrations.AddField(
            model_name='service_order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sb.Product'),
        ),
        migrations.AddField(
            model_name='product_order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sb.Customer'),
        ),
        migrations.AddField(
            model_name='product_order',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sb.Partner'),
        ),
        migrations.AddField(
            model_name='product_order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sb.Product'),
        ),
    ]
