# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 08:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0009_auto_20170421_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_order',
            old_name='note',
            new_name='snote',
        ),
        migrations.RenameField(
            model_name='service_order',
            old_name='price2Partner',
            new_name='sprice2Partner',
        ),
        migrations.RenameField(
            model_name='service_order',
            old_name='total_price',
            new_name='stotal_price',
        ),
        migrations.RenameField(
            model_name='service_order',
            old_name='validFrom',
            new_name='svalidFrom',
        ),
        migrations.RenameField(
            model_name='service_order',
            old_name='validTo',
            new_name='svalidTo',
        ),
        migrations.AlterField(
            model_name='product_order',
            name='orderDate',
            field=models.DateField(default=datetime.datetime(2017, 4, 21, 8, 3, 44, 574149, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='service_order',
            name='orderDate',
            field=models.DateField(default=datetime.datetime(2017, 4, 21, 8, 3, 44, 574149, tzinfo=utc)),
        ),
    ]
