# Generated by Django 2.0.6 on 2018-08-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0009_product_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CustomerStatus',
        ),
    ]
