# Generated by Django 2.0.6 on 2018-08-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0010_auto_20180830_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='value',
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
