# Generated by Django 2.1 on 2018-09-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0013_auto_20180902_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(max_length=500, verbose_name='待办事宜')),
                ('isfinished', models.BooleanField(default=False, verbose_name='是否已完成')),
            ],
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': '所属区县'},
        ),
        migrations.AlterModelOptions(
            name='operations',
            options={'verbose_name': '操作'},
        ),
        migrations.AlterModelOptions(
            name='ordertype',
            options={'verbose_name': '订单类型'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': '合作伙伴'},
        ),
        migrations.AlterModelOptions(
            name='paymethod',
            options={'verbose_name': '支付方法'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '产品'},
        ),
        migrations.AlterModelOptions(
            name='product_order',
            options={'verbose_name': '产品订单'},
        ),
        migrations.AlterModelOptions(
            name='service_order',
            options={'verbose_name': '服务费订单'},
        ),
        migrations.AlterModelOptions(
            name='user_extra_info',
            options={'verbose_name': '补充用户信息'},
        ),
    ]
