# Generated by Django 2.1 on 2018-09-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0014_auto_20180908_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'verbose_name': '待办事宜'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='note',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='note',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='note',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product_order',
            name='note',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service_order',
            name='snote',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_extra_info',
            name='comment',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
