# Generated by Django 2.1 on 2018-09-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0015_auto_20180908_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='operation',
            field=models.PositiveSmallIntegerField(choices=[(1, '新增'), (2, '续费'), (3, '减员')]),
        ),
    ]
